eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: ${PORT}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_ps
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      enabled: false
  application:
    name: JSR BANK

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
